### ISSUE TITLE
error message with giger_api v 0.7.4 

### ISSUE THREAD

**Issue by BananaEgg** [cyber-geiger/toolbox-communicationApi#21]
After upgrading geiger_api to 0.7.4, I'm receiving the following error message:

Error detected in pubspec.yaml:
No file or variants found for asset: packages/geiger_localstorage/lib/assets/store/store.data.

This asset was included from package geiger_api.

**Comment by martingwerder** [comment]
Hmm... asset access in Flutter is obviously still buggy. This should actually access the asset of a different package but does not seem to work in some transitive cases (funny engough: it works in some cases). 

I suspect a bug in the local cache handling of packages by Flutter. Until fixed by the Flutter developpers I will remove this dependecy. If needed you will have to place a file manually to preload the storage. Expect a new version to be published today and anounced on this issue.

**Comment by BananaEgg** [comment]
Thank you for your response, can you please provide instructions regarding this file.
What file and where it should be placed?

**Comment by martingwerder** [comment]
The resource file loads prerequisites for the indicator. It is a generic mechanism providing data if no cloud is available (so I guess you are using it in a test program without replication). The file is searched in the following locations (always relative to the current working directory which may be platform dependant):
- assets/store/store.data
- lib/assets/store/store.data 
- packages/geiger_localstorage/assets/store/store.data
- packages/geiger_localstorage/lib/assets/store/store.data


It is lookked up when the first mapper is initialized and makes sure that apart from the base nodes a minimum set of static nodes is loaded until replication is available.

A sample file with the current data may be found [in the repository](https://github.com/cyber-geiger/toolbox-stora/blob/development/lib/assets/store/store.data)

If you do not need any data an empty file will do as well

**Comment by martingwerder** [comment]
Published as 0.7.5. 

Can you confirm that the issue is gone?

**Comment by BananaEgg** [comment]
Yes, works now.
Thank you.
