### ISSUE TITLE
Storage listener only listens to the same plugin storage changes.

### ISSUE THREAD

**Issue by BananaEgg** [cyber-geiger/toolbox-communicationApi#22]
I'm trying to listen for sensor incident values stored in the toolbox, and the storage listener doesn't respond to other plugins storage events, but it reacts for my plugin storage event.
This used to work, not sure exactly when it stopped working, didn't work with 0.7.3

**Comment by luongnv89** [comment]
I can confirm that the external plugin (like Chatbot) is no longer see the storage events triggered by another external plugin (like KSP plugin). Maybe there was some change in the security so that a plugin should not see the data of other plugin?

**Comment by martingwerder** [comment]
This depends a bit on the scenario. If it is a sharing plugin this is true as sharing plugins do have access to TLP:WHITE and own data. 

If it is a non-sharing plugin it should definitely see the events. Can you elaborate on your declaration?

**Comment by BananaEgg** [comment]
I'm using  Declaration.doNotShareData

**Comment by martingwerder** [comment]
An MWE would be helpful. We try to find an issue anyway.

**Comment by BananaEgg** [comment]
You can use the sample plugin developed by @luongnv89 https://github.com/luongnv89/geiger_api_connector/tree/main/example
You could test running two instances (The package name needs to be changed to make it possible).
In the second one only activate the plugin part.

**Comment by tschai-yim** [comment]
The plugin in Luong's app doesn't receive anything because he's using the default visibility `red`. If you set it to `white` the storage event does show up. There was a bug that only enforced the visibility rules on `oldNode` which I just fixed.

Could you try the new version on `development` and see if you still see unexpected behavior?

**Comment by martingwerder** [comment]
Side fix published under 0.7.6. 

@tschai-yim: The above information is not correct. All events should be visible to non-sharing plugins regardless of the visibility. Only sharing plugins (and replication) should be constrained. Writes may be restricted due to ownership.

We probably need to correct this newly introduced logic again. Will look into it tomorrow.

**Comment by martingwerder** [comment]
Another fix for this issue is published under 0.7.7. Still looking into the logic issue... But the main problems should be fixed. Can you confirm that your part of the issue is solved (apart from the visibility issue)?

**Comment by martingwerder** [comment]
Forget it.... I just discovered that the issue runs deeper... But at least we can unit-test and reproduce it now. Publishing a fix most likely tomorrow.

**Comment by tschai-yim** [comment]
The issue should be fixed now and we'll release a patch for you to test soon. Note that Luong's connector package registers plugins as `Declaration.doShareData` and the nodes are created with `Visibility.red` so you still won't see any storage events from the chatbot example.

**Comment by BananaEgg** [comment]
Thank you @tschai-yim!
Where can I see the definition for the different visibility options, I didn't find it in the wiki.
I understood that I should be able to listen to red nodes, also see this comment from @mgwerder https://github.com/cyber-geiger/toolbox-communicationApi/issues/22#issuecomment-1091458597 
According to my understanding the Declaration.doShareData only impacts the data that can be read by that plugin and not any other plugins reading the data.

**Comment by martingwerder** [comment]
It is nowhere stated explicitely how sharing declaration applies to visibility. Some parts are covered in the replication part but this is only a fraction. I created a new issue #24 to make sure that documentation on this is done.

**Comment by martingwerder** [comment]
Is this issue solved or do you still experience troubles with the most recent release?

**Comment by luongnv89** [comment]
I have set the visibility of the data node to be `white`, GOOD NEWS is it seems that the problem has been gone. However I still have one question regarding the visibility of the node (tree). Suppose that I want to share my data node at: `:Chatbot:sensors:ksp-tool:threats`, then when I prepare the root path: `:Chatbot:sensors:ksp-tool`, do I have to set the visibility to `white` for each node up to the root?

Many thanks,

**Comment by luongnv89** [comment]
Hi, after some careful test, I think the problem is still persist. @BananaEgg please make some more tests to confirm.
I have tested with `geiger_localstorage: 0.6.49` and `geiger_api: 0.7.8`. An external plugin still cannot see the storage event of another external plugin. Even though I have set the visibility of whole tree to be 'white'.

**Comment by BananaEgg** [comment]
Just tested and it works!
Thank you all!
